In [21]:
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
import random
from sklearn import svm
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential, save_model, load_model
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau


In [22]:
def load_data():
    vowels = {
                'अ': 'a',
                'आ': 'ā',
                'इ': 'i',
                'ई': 'ī',
                'उ': 'u',
                'ऊ': 'ū',
                'ऋ': 'ṛ',
                'ॠ': 'ṝ',
                'ऌ': 'ḷ',
                'ॡ': 'ḹ',
                'ए': 'e',
                'ऐ': 'ai',
                'ओ': 'o',
                'औ': 'au'
            }
    images = []
    labels = []
    test_images = []
    test_labels = []
    for i in vowels:
        path = f'my_data/{vowels[i]}'
        files = os.listdir(path)
        random.shuffle(files)
        for j, image in enumerate(files):
            try:
                imagePath = os.path.join(path, image)
                img = cv2.imread(imagePath, cv2.IMREAD_GRAYSCALE)
                img = cv2.resize(img, (32,32))
                img = img.astype('float32') / 255.0
                # img = img.flatten()
                if j < 32:
                    images.append(img)
                    labels.append(i)
                elif j >= 32:
                    test_images.append(img)
                    test_labels.append(i)
                else:
                    break
            except:
                print(f"file {image} not working :(")
        print(path)
    return np.array(images), np.array(labels), np.array(test_images), np.array(test_labels)

In [23]:
images, labels, test_images, test_labels = load_data()
print("Images shape:", images.shape)
print("Labels shape:", labels.shape)
print("TestImages shape:", test_images.shape)
print("TestLabels shape:", test_labels.shape)


my_data/a
my_data/ā
my_data/i
my_data/ī
my_data/u
my_data/ū
my_data/ṛ
my_data/ṝ
my_data/ḷ
my_data/ḹ
my_data/e
my_data/ai
my_data/o
my_data/au
Images shape: (448, 32, 32)
Labels shape: (448,)
TestImages shape: (163, 32, 32)
TestLabels shape: (163,)


In [24]:
train_data =  list(zip(images, labels))
random.shuffle(train_data)
X_train, y_train = zip(*train_data)
test_data =  list(zip(test_images, test_labels))
random.shuffle(test_data)
X_test, y_test = zip(*test_data)

In [28]:
print(X_train[0])
import matplotlib.pyplot as plt

plt.show(X_train[0] )

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
svm_classifier = svm.SVC(kernel='linear')

# Train the SVM model
svm_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred))


ValueError: Found array with dim 3. SVC expected <= 2.

In [ ]:
k = 5  # Number of neighbors to consider
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Train the k-NN model
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.22085889570552147
Classification Report:
               precision    recall  f1-score   support

           अ       0.23      0.13      0.17        23
           आ       0.11      0.11      0.11         9
           इ       0.47      0.44      0.45        16
           ई       0.00      0.00      0.00        11
           उ       0.35      0.35      0.35        20
           ऊ       0.00      0.00      0.00         8
           ऋ       0.16      0.50      0.24        18
           ऌ       0.33      0.12      0.18         8
           ए       0.12      0.50      0.19         8
           ऐ       1.00      0.06      0.12        16
           ओ       0.00      0.00      0.00         9
           औ       1.00      0.12      0.22         8
           ॠ       0.67      0.25      0.36         8
           ॡ       0.00      0.00      0.00         1

    accuracy                           0.22       163
   macro avg       0.32      0.19      0.17       163
weighted avg       0.35   

/home/kaustubhg73/Desktop/5th Semester/Project-I/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/kaustubhg73/Desktop/5th Semester/Project-I/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/kaustubhg73/Desktop/5th Semester/Project-I/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this 

In [ ]:
# Initialize the Decision Tree classifier
decision_tree_classifier = DecisionTreeClassifier(random_state=42)

# Train the Decision Tree model
decision_tree_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = decision_tree_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.1901840490797546
Classification Report:
               precision    recall  f1-score   support

           अ       0.18      0.13      0.15        23
           आ       0.25      0.22      0.24         9
           इ       0.25      0.19      0.21        16
           ई       0.40      0.36      0.38        11
           उ       0.25      0.15      0.19        20
           ऊ       0.00      0.00      0.00         8
           ऋ       0.10      0.11      0.11        18
           ऌ       0.00      0.00      0.00         8
           ए       0.67      0.25      0.36         8
           ऐ       0.33      0.31      0.32        16
           ओ       0.08      0.11      0.10         9
           औ       0.40      0.50      0.44         8
           ॠ       0.12      0.25      0.17         8
           ॡ       0.00      0.00      0.00         1

    accuracy                           0.19       163
   macro avg       0.22      0.18      0.19       163
weighted avg       0.23    

In [ ]:
# Initialize the Random Forest classifier
random_forest_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the Random Forest model
random_forest_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = random_forest_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.43558282208588955
Classification Report:
               precision    recall  f1-score   support

           अ       0.38      0.22      0.28        23
           आ       0.21      0.33      0.26         9
           इ       0.50      0.75      0.60        16
           ई       0.70      0.64      0.67        11
           उ       0.47      0.35      0.40        20
           ऊ       0.20      0.12      0.15         8
           ऋ       0.38      0.33      0.35        18
           ऌ       0.20      0.12      0.15         8
           ए       0.38      0.75      0.50         8
           ऐ       0.71      0.75      0.73        16
           ओ       0.50      0.11      0.18         9
           औ       0.54      0.88      0.67         8
           ॠ       0.43      0.38      0.40         8
           ॡ       0.00      0.00      0.00         1

    accuracy                           0.44       163
   macro avg       0.40      0.41      0.38       163
weighted avg       0.44   

In [ ]:
# Initialize the Multinomial Naive Bayes classifier
naive_bayes_classifier = MultinomialNB()

# Train the Naive Bayes model
naive_bayes_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = naive_bayes_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print a detailed classification report
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.4049079754601227
Classification Report:
               precision    recall  f1-score   support

           अ       0.30      0.13      0.18        23
           आ       0.19      0.33      0.24         9
           इ       0.50      0.56      0.53        16
           ई       0.88      0.64      0.74        11
           उ       0.75      0.45      0.56        20
           ऊ       0.25      0.25      0.25         8
           ऋ       0.46      0.33      0.39        18
           ऌ       0.12      0.12      0.12         8
           ए       0.38      0.75      0.50         8
           ऐ       0.59      0.62      0.61        16
           ओ       0.33      0.33      0.33         9
           औ       0.67      0.50      0.57         8
           ॠ       0.21      0.38      0.27         8
           ॡ       0.00      0.00      0.00         1

    accuracy                           0.40       163
   macro avg       0.40      0.39      0.38       163
weighted avg       0.46    

In [ ]:
cnn = Sequential()
cnn.add(Conv2D(filters=32, kernel_size=(3, 3), padding='same', strides=(1,1), activation='relu', input_shape=(32, 32, 1)))
cnn.add(Dropout(.2))
cnn.add(MaxPool2D(pool_size=(2, 2), strides=(2, 2)))
cnn.add(Conv2D(filters=64, kernel_size=(3, 3), padding='same', strides=(1,1), activation='relu'))
cnn.add(Dropout(.2))
cnn.add(MaxPool2D(pool_size=(2, 2), strides=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=128, activation='relu'))
cnn.add(Dropout(.5))
cnn.add(Dense(units=10, activation='softmax'))

plot_model(cnn, show_shapes=True, show_layer_activations=True, show_layer_names=False)

2023-11-09 21:36:16.882767: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-09 21:36:17.049307: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [ ]:
cnn.compile(optimizer=Adam(learning_rate=0.001),
            loss=CategoricalCrossentropy(from_logits=True),
            metrics=CategoricalAccuracy())

cnn.fit(X_train, y_train)

IndexError: tuple index out of range